sudo: required

services:
  - docker

before_install:
  - sh ./.docker_image.sh build

script:
  - sh ./.docker_image.sh show

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - sh ./.docker_image.sh push
